package com.techelevator.model.reservation;

import java.time.LocalDate;

public interface ReservationDAO {


	

	
	
	
	/*********************************************
	 * Insert reservation into database table    *
	 *      given the site_id and dates          *
	 * Reservation ID will then be autogenerated *
	 ********************************************/
	
	public void saveReservation(Reservation newReservation);
	
	
	

	
}
